MVCTASK/Controllers/CourseController.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace MVCTASK.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICoursesService _coursesService;
        private readonly IDepartmentsService _departmentsService;
        //private readonly AppDbContext _context;
        public CourseController(ICoursesService coursesService , IDepartmentsService departmentsService)
        {
            _departmentsService = departmentsService;
            _coursesService = coursesService;
            //_context = context;
        }
        public IActionResult Search(string Name, int? DepartmentId)
        {
            var courses = _coursesService.Search(Name);
            return View("Index", courses);
        }
      
        public IActionResult Index()
        {
            var Courses = _coursesService.GetAll();
            return View(Courses);
        }
        public IActionResult Result(int id)
        {
            //IEnumerable<CrsReselt> CR = _context.crsReselts.AsNoTracking().Include(c => c.Course).Include(t => t.Trainee).Where(c => c.CourseId == id);

            //List<CourseResultVM> CRVM = new List<CourseResultVM>();
            //foreach (var c in CR)
            //{
            //    CourseResultVM cVM = new CourseResultVM()
            //    {
            //        trainee = c.Trainee.Name,
            //        Course = c.Course.Name,
            //        color = c.Course.MinDegree > c.Gredee ? "red" : "blue"
            //    };
            //    CRVM.Add(cVM);
            //}
            //return View(CRVM);
            return View();
        }
        [HttpGet]
        public IActionResult Add()
        {
            AddCourseVM addCourseVM = new AddCourseVM()
            {
                Departments = _departmentsService.GetDepartments()
            };
            return View(addCourseVM);
        }
        [HttpPost]
        public IActionResult Add(AddCourseVM model)
        {
            if (!ModelState.IsValid)
            {
                AddCourseVM addCourseVM = new AddCourseVM()
                {
                    Degree = model.Degree,
                    Hour = model.Hour,
                    DepartmentId = model.DepartmentId,
                    MinDegree = model.MinDegree,
                    Name = model.Name,
                    Departments = _departmentsService.GetDepartments()
                };
                return View(addCourseVM);
            }
            _coursesService.Add(model);
            int c=  _coursesService.save();

            //Course CRS = new Course()
            //{
            //    Name = model.Name,
            //    MinDegree = model.MinDegree,
            //    DepartmentId = model.DepartmentId,
            //    Degree = model.Degree,
            //    Hour = (int)model.Hour,

            //};
            //_context.Add(CRS);
            //_context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult CheckDegree(int Degree ,int MinDegree) 
        {
            if (Degree <= 100 && Degree >= 50 && MinDegree <Degree)
            {
                
                return Json(true);
            }
            return Json(false);
        }
        public IActionResult Edit(int id)
        {
            var c = _coursesService.GetbyId(id);
            EditCourseVM editCourseVM = new EditCourseVM()
            {
                id = id,
                Name = c!.Name,
                MinDegree = c!.MinDegree,
                DepartmentId = c!.DepartmentId,
                Degree = c!.Degree,
                Hour = (int)c!.Hour,
                Departments = _departmentsService.GetDepartments()
            };
            return View(editCourseVM);
        }
        [HttpPost]
        public IActionResult Edit(EditCourseVM model)
        {
            if (!ModelState.IsValid)
            {
                EditCourseVM editCourseVM = new EditCourseVM()
                {
                    id = model.id,
                    Name = model.Name,
                    MinDegree = model.MinDegree,
                    DepartmentId = model.DepartmentId,
                    Degree = model.Degree,
                    Hour = (int)model.Hour,
                    Departments = _departmentsService.GetDepartments()
                };
                return View(editCourseVM);
            }
            _coursesService.Edit(model);
            _coursesService.save();
            //var c = _context.courses.FirstOrDefault(x=>x.Id == model.id);
            //c.Degree=model.Degree;
            //c.Hour=model.Hour;
            //c.DepartmentId=model.DepartmentId;
            //c.MinDegree =model.MinDegree;
            //c.Name=model.Name;
            //_context.Update(c);
            //_context.SaveChanges();
            return RedirectToAction(nameof(Index));
            
        }

        public IActionResult Remove(int id)
        {
            _coursesService.delete(id);
            _coursesService.save();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult ValidateHour(int hour)
        {
            if (hour % 3 == 0 && hour != 0) 
            {
                return Json(true);
            }
            return Json(false);
        }
    }
}

MVCTASK/Controllers/InstructorController.cs
using System.Data;


namespace MVCTASK.Controllers
{
    public class InstructorController : Controller
    {
        private readonly IInstructorsService _instructorsService;
        private readonly ICoursesService _coursesService;
        private readonly AppDbContext _Context;
        public InstructorController(IInstructorsService instructorsService, AppDbContext context ,ICoursesService coursesService)
        {
            _coursesService = coursesService;
            _instructorsService = instructorsService;
            _Context = context;
        }
        public IActionResult Index(int num)
        {
            int totalpage;
            int n;
            var listinst = _instructorsService.GetInstructorsByPage(num, out totalpage, out n).ToList();
            ViewBag.totalpage = totalpage;
            ViewBag.number = n;
            return View(listinst);
        }
        public IActionResult Details(int id)
        {
            var instructor = _instructorsService.GetById(id);
            return View(instructor);
        }
        [HttpGet]
        public IActionResult Add()
        {
            AddInstVM addInstVM = new AddInstVM();
            addInstVM.Departments = _Context.departments.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).OrderBy(x => x.Text).AsNoTracking().ToList();
            addInstVM.Courses = new List<SelectListItem>();
            // addInstVM.Courses = _Context.courses.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).OrderBy(x => x.Text).AsNoTracking().ToList();
            return View(addInstVM);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddInstVM model)
        {
            if (!ModelState.IsValid)
            {
                AddInstVM addInstVM = new AddInstVM();
                addInstVM.Departments = _Context.departments.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).OrderBy(x => x.Text).AsNoTracking().ToList();
                if (model.DepartmentId != 0)
                {
                    model.Courses = _Context.courses
                        .Where(c => c.DepartmentId == model.DepartmentId)
                        .Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name })
                        .OrderBy(x => x.Text)
                        .AsNoTracking()
                        .ToList();
                }
                else
                {
                    model.Courses = new List<SelectListItem>();
                }
                // addInstVM.Courses = _Context.courses.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).OrderBy(x => x.Text).AsNoTracking().ToList();
                return View(addInstVM);
            }
            var result = await _instructorsService.Add(model);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var inst = _instructorsService.GetById(id);
            EditInstVm editInstVm = new EditInstVm();
            editInstVm.id = inst!.Id;
            editInstVm.Address = inst.Address;
            editInstVm.CrsId = inst.CrsId;
            editInstVm.Name = inst.Name;
            editInstVm.Salary = inst.Salary;
            editInstVm.DepartmentId = inst.DepartmentId;
            editInstVm.CuruntImg = inst.Img;
            editInstVm.Departments = _Context.departments.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).OrderBy(x => x.Text).AsNoTracking().ToList();
            editInstVm.Courses = _Context.courses.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).OrderBy(x => x.Text).AsNoTracking().ToList();
            return View(editInstVm);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditInstVm model)
        {
            if (!ModelState.IsValid)
            {
                EditInstVm editInstVm = new EditInstVm();
                editInstVm.Departments = _Context.departments.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).OrderBy(x => x.Text).AsNoTracking().ToList();
                editInstVm.Courses = _Context.courses.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).OrderBy(x => x.Text).AsNoTracking().ToList();
                return View(editInstVm);
            }
            await _instructorsService.Edit(model);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult GetCoursesByDepartment(int deptId)
        {
            var courses = _coursesService.GetCoursesByDptId(deptId);

            return Json(courses);
        }

    }
}

MVCTASK/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCTASK</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCTASK.styles.css" asp-append-version="true" />
</head>
<body>
   <partial name="_NavPartial"></partial>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MVCTASK - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCTASK/Views/Shared/_NavPartial.cshtml
 <header>
       <nav   class="navbar navbar-expand-lg bg-primary mb-3" >
        @* class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow "> *@
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCTASK</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text" asp-area="" asp-controller="Home" asp-action="index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text" asp-area="" asp-controller="Instructor" asp-action="Index" asp-route-num="1">Instructors</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text" asp-area="" asp-controller="Course" asp-action="index" asp-route-num="1">Courses</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>